### ISSUE TITLE
Miscellaneous task for 1.8

### ISSUE THREAD

**Issue by larskuhtz** [kadena-io/chainweb-node#1009]
# TODO

* [ ] confirm fork height for feature flag enforcement
* [ ] increase default value block gas limit

# 20 chains rollout preparation

* [ ] publish road map, so miners, pools, and exchanges can update their integration code
* [ ] document new block header format (size change)
* [ ] inform miners about the change and make sure that existing mining clients can deal
    with the new block format/size.
* [ ] consider making mining work size independent of block size by first hashing (some of) the work before joining the nonce. 

# Miscellaneous Changes (needs triage)

* [ ] make epoch time accumulation incremental
* [ ] limit SPV chain oracle query depth during pact validation of proofs
* [ ] fix database directory configuration
* [ ] hide amber data from config
* [ ] consider hiding all "disabled" components from `--print-config`
